controller_manager:
  ros__parameters:
    update_rate: 30

    diff_drive_base_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_drive_base_controller:
  ros__parameters:
    left_wheel_names: ["wheel_front_left_joint", "wheel_back_left_joint"]
    right_wheel_names: ["wheel_front_right_joint", "wheel_back_right_joint"]

    wheel_separation: 0.123
    wheel_radius: 0.0406

    linear.x.has_velocity_limits: true
    linear.x.max_velocity: 2.0
    angular.z.has_velocity_limits: true
    angular.z.max_velocity: 2.0

    use_stamped_vel: false

    publish_rate: 30.0
    base_frame_id: base_footprint
    odom_frame_id: odom
    enable_odom_tf: true
